"""Build the Visual Studio 2022 Dark theme descriptor for Rider.

Takes Rider's own New UI dark theme (``expUI_dark.theme.json``) from the local
installation as the key skeleton, recolours it with the Visual Studio palette
(:mod:`vs_palette`), pins the signature surfaces, attaches the icon pack
mappings produced by ``tools/gen_icons.py`` and writes the final
``.theme.json`` into the plugin resources.

Usage:
    python tools/build_theme.py            # 2026.1 install, auto-detected
    python tools/build_theme.py --base <path-to-theme.json>
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import vs_palette as vp

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BASE = ROOT / "ref" / "themes" / "expUI_dark.theme.json"
OUT = ROOT / "src" / "main" / "resources" / "themes" / "visual-studio-2022-dark.theme.json"
ICON_MAP = ROOT / "build" / "icon-map.json"

RAMP_RE = re.compile(r"^([A-Z][a-z]+)(\d+)$")


def recolour_palette(colours: dict[str, str]) -> tuple[dict[str, str], list[str]]:
    """Rewrite the base theme's palette variables with Visual Studio ramps."""
    out, unknown = {}, []
    for name, value in colours.items():
        match = RAMP_RE.match(name)
        if match and match.group(1) in vp.RAMP:
            ramp = vp.RAMP[match.group(1)]
            index = int(match.group(2))
            out[name] = ramp[min(index, len(ramp)) - 1]
        else:
            out[name] = value
            unknown.append(name)
    return out, unknown


def flatten(node: dict, prefix: str = "") -> list[str]:
    paths = []
    for key, value in node.items():
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            paths.extend(flatten(value, path))
        else:
            paths.append(path)
    return paths


def set_path(node: dict, path: str, value) -> None:
    parts = path.split(".")
    cursor = node
    for part in parts[:-1]:
        cursor = cursor.setdefault(part, {})
    cursor[parts[-1]] = value


def build(base_path: Path, icon_map_path: Path) -> dict:
    base = json.loads(base_path.read_text(encoding="utf-8"))
    ui = base["ui"]

    ui = json.loads(json.dumps(ui))  # deep copy, we are going to mutate it

    palette, unknown = recolour_palette(base.get("colors", {}))
    known_paths = set(flatten(base["ui"]))

    added = []
    for path, value in vp.SIGNATURE.items():
        if path not in known_paths:
            added.append(path)
        set_path(ui, path, value)

    theme = {
        "name": "Sharp Studio Dark",
        "dark": True,
        "author": "hojjat nikan (generated by rider-vs-theme)",
        # No "parentTheme" declaration: the theme inherits the standard New UI
        # dark chain on its own, which keeps Rider's own component UI classes
        # (dialog option buttons, disclosure buttons, ...) intact.
        # The theme points at Rider's bundled scheme (guaranteed to resolve, so the
        # editor never falls back to an unrelated scheme).  The installer also drops
        # "Sharp Studio Dark" into the user's colorSchemes folder -- that is the
        # scheme the IDE actually selects, and the name the user sees.
        "editorScheme": "Visual Studio Dark",
        "colors": palette,
        "ui": ui,
    }

    icons: dict[str, object] = {}
    if icon_map_path.exists():
        mapping = json.loads(icon_map_path.read_text(encoding="utf-8"))
        icons.update(mapping.get("paths", {}))
    icons["ColorPalette"] = vp.ICON_PALETTE
    theme["icons"] = icons

    print(f"base palette variables : {len(palette)} (kept as-is: {len(unknown)})")
    print(f"base ui entries        : {len(known_paths)}")
    print(f"signature keys pinned  : {len(vp.SIGNATURE)} (new keys: {len(added)})")
    print(f"icon path mappings     : {len(icons) - 1}")
    if added:
        print("  new keys: " + ", ".join(added[:12]) + (" ..." if len(added) > 12 else ""))
    return theme


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default=str(DEFAULT_BASE))
    ap.add_argument("--icons", default=str(ICON_MAP))
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    theme = build(Path(args.base), Path(args.icons))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(theme, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"\nwrote {out} ({out.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
